### ISSUE TITLE
Accept URLs with query strings attached

### ISSUE THREAD

**Issue by tomasz1986** [ungoogled-extension/ungoogled-extension.github.io#1]
Would it be possible to automatically strip query strings from the extension URLs?

Many times, e.g. when searching in Google, the extension URLs come up with a language query string attached, like the URL below with `?hl=en` attached to it.

```
https://chrome.google.com/webstore/detail/ublock-origin-extra/pgdnlhfefecpicbbihgmbmffkjpaplco?hl=en
```

Right now, when this kind of an URL is pasted to the input field, an error pops up upon clicking the `Install` button.

```
error-invalidAppId
Error 404
```

**Comment by jieggii** [comment]
You are right, thank you. I am going to fix it in a few days

**Comment by jieggii** [comment]
Fixed it in [this commit](https://github.com/ungoogled-extension/ungoogled-extension.github.io/commit/95fdf8d3e25ec0744f7d313ddecd1571f9bcf8c5).
