### ISSUE TITLE
Installation of extensions does not work

### ISSUE THREAD

**Issue by Bu4ak** [ungoogled-extension/ungoogled-extension.github.io#2]
![изображение](https://user-images.githubusercontent.com/17143820/84624926-942c6200-aee2-11ea-9b66-61b2e01ef2e4.png)
___
`Version 81.0.4044.138 (Developer Build) built on Ubuntu bionic/18.04, running on neon bionic/18.04 (64-bit)
`

**Comment by jieggii** [comment]
Hello. Thank you for issue. I haven't used the website for a long time and it seems that this installation method doesn't work anymore. I am going to try to fix it or find some alternatives.

**Comment by Bu4ak** [comment]
I downloaded extension using your page, unpacked extension using http://crxextractor.com/, unpacked zip, opened `chrome://extensions/` in chromium, and install via `Load unpacked` button

**Comment by jieggii** [comment]
Well, I've googled and tested a bit. In my opinion, the best way to install extensions on ungoogled chromium is to use this extension: https://github.com/NeverDecaf/chromium-web-store. It works just fine.
